export const MetadataKeys = {
  FORM_FIELD: 'LIBERTY_FORM_FIELD',
  FIELDS: 'LIBERTY_FORM_FIELDS',
  HINT: 'LIBERTY_HINT',
  DISPLAY_NAME: 'LIBERTY_DISPLAY_NAME',
  PLACEHOLDER: 'LIBERTY_PLACEHOLDER',
  RADIO_OPTIONS: 'LIBERTY_RADIO_OPTIONS',
  TEXTAREA_OPTIONS: 'LIBERTY_AREA_OPTIONS',
};
